name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Release APK
      run: ./gradlew assembleRelease --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: crossmeds-apk
        path: app/build/outputs/apk/release/app-release.apk
